"""add_assets_preview_and_ml_statuses

Revision ID: 029ea5e4f38a
Revises: c1402c059e2a
Create Date: 2026-04-21 12:04:50.513626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '029ea5e4f38a'
down_revision: Union[str, Sequence[str], None] = 'c1402c059e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('preview_status', sa.String(length=32), nullable=False))
    op.add_column('assets', sa.Column('preview_error', sa.Text(), nullable=True))
    op.add_column('assets', sa.Column('faces_status', sa.String(length=32), nullable=False))
    op.add_column('assets', sa.Column('faces_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'faces_error')
    op.drop_column('assets', 'faces_status')
    op.drop_column('assets', 'preview_error')
    op.drop_column('assets', 'preview_status')
    # ### end Alembic commands ###
