"""add_asset_version_description

Revision ID: 0c6be6f379af
Revises: cd2883e5d45f
Create Date: 2026-06-01 22:14:41.287572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6be6f379af'
down_revision: Union[str, Sequence[str], None] = 'cd2883e5d45f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_versions', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_versions', 'description')
    # ### end Alembic commands ###
