"""add_asset_lifecycle_status

Revision ID: 44b1eba807d2
Revises: 5942d9d6af35
Create Date: 2026-05-01 17:12:41.784402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44b1eba807d2'
down_revision: Union[str, Sequence[str], None] = '5942d9d6af35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('lifecycle_status', sa.String(length=32), nullable=False))
    op.add_column('assets', sa.Column('trashed_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('assets', sa.Column('trashed_by_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'assets', 'users', ['trashed_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_column('assets', 'trashed_by_user_id')
    op.drop_column('assets', 'trashed_at')
    op.drop_column('assets', 'lifecycle_status')
    # ### end Alembic commands ###
