"""all_statuse_moved_to_asset_versions

Revision ID: 5942d9d6af35
Revises: c2693c01fc31
Create Date: 2026-04-28 18:53:32.037752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5942d9d6af35'
down_revision: Union[str, Sequence[str], None] = 'c2693c01fc31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_versions', sa.Column('base_version_id', sa.UUID(), nullable=True))
    op.add_column('asset_versions', sa.Column('status', sa.String(length=32), nullable=False))
    op.add_column('asset_versions', sa.Column('preview_status', sa.String(length=32), nullable=False))
    op.add_column('asset_versions', sa.Column('preview_error', sa.Text(), nullable=True))
    op.add_column('asset_versions', sa.Column('faces_status', sa.String(length=32), nullable=False))
    op.add_column('asset_versions', sa.Column('faces_error', sa.Text(), nullable=True))
    op.add_column('asset_versions', sa.Column('rendered_width', sa.Integer(), nullable=True))
    op.add_column('asset_versions', sa.Column('rendered_height', sa.Integer(), nullable=True))
    op.add_column('asset_versions', sa.Column('is_identity_source', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'asset_versions', 'asset_versions', ['base_version_id'], ['id'], ondelete='SET NULL')
    op.drop_column('assets', 'faces_status')
    op.drop_column('assets', 'faces_error')
    op.drop_column('assets', 'preview_error')
    op.drop_column('assets', 'status')
    op.drop_column('assets', 'preview_status')
    op.add_column('face_detections', sa.Column('asset_version_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'face_detections', 'asset_versions', ['asset_version_id'], ['id'], ondelete='CASCADE')
    op.add_column('files', sa.Column('asset_version_id', sa.UUID(), nullable=True))
    op.create_unique_constraint('uq_file_asset_version_purpose', 'files', ['asset_version_id', 'purpose'])
    op.create_foreign_key(None, 'files', 'asset_versions', ['asset_version_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_constraint('uq_file_asset_version_purpose', 'files', type_='unique')
    op.drop_column('files', 'asset_version_id')
    op.drop_constraint(None, 'face_detections', type_='foreignkey')
    op.drop_column('face_detections', 'asset_version_id')
    op.add_column('assets', sa.Column('preview_status', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('assets', sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('assets', sa.Column('preview_error', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('assets', sa.Column('faces_error', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('assets', sa.Column('faces_status', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'asset_versions', type_='foreignkey')
    op.drop_column('asset_versions', 'is_identity_source')
    op.drop_column('asset_versions', 'rendered_height')
    op.drop_column('asset_versions', 'rendered_width')
    op.drop_column('asset_versions', 'faces_error')
    op.drop_column('asset_versions', 'faces_status')
    op.drop_column('asset_versions', 'preview_error')
    op.drop_column('asset_versions', 'preview_status')
    op.drop_column('asset_versions', 'status')
    op.drop_column('asset_versions', 'base_version_id')
    # ### end Alembic commands ###
