"""add_face_candidates_and_model_identity

Revision ID: 679a02af1725
Revises: 6c389c3d5e7e
Create Date: 2026-04-14 19:15:30.190541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '679a02af1725'
down_revision: Union[str, Sequence[str], None] = '6c389c3d5e7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('face_detection_id', sa.UUID(), nullable=False),
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['face_detection_id'], ['face_detections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['identity_id'], ['face_identities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('face_detections', sa.Column('model_identity_id', sa.UUID(), nullable=True))
    op.add_column('face_detections', sa.Column('model_identity_score', sa.Float(), nullable=True))
    op.add_column('face_detections', sa.Column('model_identity_margin', sa.Float(), nullable=True))
    op.add_column('face_detections', sa.Column('assignment_source', sa.String(length=16), nullable=True))
    op.create_foreign_key(None, 'face_detections', 'face_identities', ['model_identity_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'face_detections', type_='foreignkey')
    op.drop_column('face_detections', 'assignment_source')
    op.drop_column('face_detections', 'model_identity_margin')
    op.drop_column('face_detections', 'model_identity_score')
    op.drop_column('face_detections', 'model_identity_id')
    op.drop_table('face_candidates')
    # ### end Alembic commands ###
