"""face_identities table

Revision ID: 6c389c3d5e7e
Revises: fc091496fbe6
Create Date: 2026-04-14 10:34:39.140019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '6c389c3d5e7e'
down_revision: Union[str, Sequence[str], None] = 'fc091496fbe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('cover_face_id', sa.UUID(), nullable=True),
    sa.Column('centroid_embedding', Vector(128), nullable=True),
    sa.Column('samples_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cover_face_id'], ['face_detections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('face_detections', sa.Column('identity_id', sa.UUID(), nullable=True))
    op.add_column('face_detections', sa.Column('face_index', sa.Integer(), nullable=False))
    op.add_column('face_detections', sa.Column('quality_score', sa.Float(), nullable=True))
    op.add_column('face_detections', sa.Column('identity_score', sa.Float(), nullable=True))
    op.add_column('face_detections', sa.Column('is_reference', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('face_detections_person_id_fkey'), 'face_detections', type_='foreignkey')
    op.create_foreign_key(None, 'face_detections', 'face_identities', ['identity_id'], ['id'], ondelete='SET NULL')
    op.drop_column('face_detections', 'person_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face_detections', sa.Column('person_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'face_detections', type_='foreignkey')
    op.create_foreign_key(op.f('face_detections_person_id_fkey'), 'face_detections', 'persons', ['person_id'], ['id'], ondelete='SET NULL')
    op.drop_column('face_detections', 'is_reference')
    op.drop_column('face_detections', 'identity_score')
    op.drop_column('face_detections', 'quality_score')
    op.drop_column('face_detections', 'face_index')
    op.drop_column('face_detections', 'identity_id')
    op.drop_table('face_identities')
    # ### end Alembic commands ###
