"""add_crop_path_to_face_detections

Revision ID: 74c6be885806
Revises: 679a02af1725
Create Date: 2026-04-15 18:17:59.628765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74c6be885806'
down_revision: Union[str, Sequence[str], None] = '679a02af1725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face_detections', sa.Column('crop_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('face_detections', 'crop_path')
    # ### end Alembic commands ###
