"""add_asset_version_semantic_embedding

Revision ID: 89bfa779e88f
Revises: f1795424dbca
Create Date: 2026-05-04 17:45:43.383382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '89bfa779e88f'
down_revision: Union[str, Sequence[str], None] = 'f1795424dbca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_versions', sa.Column('semantic_embedding', Vector(512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_versions', 'semantic_embedding')
    # ### end Alembic commands ###
