"""face_detections_512_embedding_vector

Revision ID: c2693c01fc31
Revises: c718788cf9f6
Create Date: 2026-04-24 12:08:30.715745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'c2693c01fc31'
down_revision: Union[str, Sequence[str], None] = 'c718788cf9f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('face_detections', 'embedding',
               existing_type=Vector(dim=128),
               type_=Vector(dim=512),
               existing_nullable=False)
    op.alter_column('face_identities', 'centroid_embedding',
               existing_type=Vector(dim=128),
               type_=Vector(dim=512),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('face_identities', 'centroid_embedding',
               existing_type=Vector(dim=512),
               type_=Vector(dim=128),
               existing_nullable=True)
    op.alter_column('face_detections', 'embedding',
               existing_type=Vector(dim=512),
               type_=Vector(dim=128),
               existing_nullable=False)
    # ### end Alembic commands ###
