"""exif, iptc, xmp, other fields

Revision ID: c53283ffdcd8
Revises: 95577362cc26
Create Date: 2026-03-29 15:54:13.984169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c53283ffdcd8'
down_revision: Union[str, Sequence[str], None] = '95577362cc26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_versions', sa.Column('exif', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('asset_versions', sa.Column('iptc', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('asset_versions', sa.Column('xmp', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('asset_versions', sa.Column('other', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('asset_versions', 'exif_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_versions', sa.Column('exif_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('asset_versions', 'other')
    op.drop_column('asset_versions', 'xmp')
    op.drop_column('asset_versions', 'iptc')
    op.drop_column('asset_versions', 'exif')
    # ### end Alembic commands ###
