"""add_face_detections_review_statuses_fields

Revision ID: c718788cf9f6
Revises: 029ea5e4f38a
Create Date: 2026-04-23 10:11:52.126334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c718788cf9f6'
down_revision: Union[str, Sequence[str], None] = '029ea5e4f38a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face_detections', sa.Column('review_state', sa.String(length=32), nullable=False))
    op.add_column('face_detections', sa.Column('review_required', sa.Boolean(), nullable=False))
    op.add_column('face_detections', sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True))
    op.add_column('face_detections', sa.Column('reviewed_at', sa.TIMESTAMP(), nullable=True))
    op.create_foreign_key(None, 'face_detections', 'users', ['reviewed_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'face_detections', type_='foreignkey')
    op.drop_column('face_detections', 'reviewed_at')
    op.drop_column('face_detections', 'reviewed_by_user_id')
    op.drop_column('face_detections', 'review_required')
    op.drop_column('face_detections', 'review_state')
    # ### end Alembic commands ###
