"""add_asset_duplicate_candidates_and_new_asset_fields

Revision ID: f1795424dbca
Revises: 44b1eba807d2
Create Date: 2026-05-01 19:48:58.458628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1795424dbca'
down_revision: Union[str, Sequence[str], None] = '44b1eba807d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_duplicate_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_asset_id', sa.UUID(), nullable=False),
    sa.Column('candidate_asset_id', sa.UUID(), nullable=False),
    sa.Column('duplicate_type', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('review_decision', sa.String(length=32), nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_asset_id', 'candidate_asset_id', name='uq_asset_duplicate_candidate_pair')
    )
    op.add_column('asset_versions', sa.Column('sha256', sa.String(length=64), nullable=True))
    op.add_column('asset_versions', sa.Column('phash', sa.String(length=32), nullable=True))
    op.add_column('asset_versions', sa.Column('dhash', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_asset_versions_dhash'), 'asset_versions', ['dhash'], unique=False)
    op.create_index(op.f('ix_asset_versions_phash'), 'asset_versions', ['phash'], unique=False)
    op.create_index(op.f('ix_asset_versions_sha256'), 'asset_versions', ['sha256'], unique=False)
    op.add_column('assets', sa.Column('duplicate_review_status', sa.String(length=32), nullable=False))
    op.add_column('assets', sa.Column('duplicate_of_asset_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'assets', 'assets', ['duplicate_of_asset_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_column('assets', 'duplicate_of_asset_id')
    op.drop_column('assets', 'duplicate_review_status')
    op.drop_index(op.f('ix_asset_versions_sha256'), table_name='asset_versions')
    op.drop_index(op.f('ix_asset_versions_phash'), table_name='asset_versions')
    op.drop_index(op.f('ix_asset_versions_dhash'), table_name='asset_versions')
    op.drop_column('asset_versions', 'dhash')
    op.drop_column('asset_versions', 'phash')
    op.drop_column('asset_versions', 'sha256')
    op.drop_table('asset_duplicate_candidates')
    # ### end Alembic commands ###
